### ISSUE TITLE
socketio reconnection problem

### ISSUE THREAD

**Issue by rhfeiyang** [iamhyc/Overleaf-Workshop#23]
Hi, I found that when I use cookie to login in overleaf.com to edit my projects, it will be disconnected from overleaf.com after a while(the new edits will not be synchronized to remote).  I have to restart the vscode to continue... (

**Comment by iamhyc** [comment]
Hi, if your login is still valid after you restart VSCode, the cookie is still working and there is ***no bug*** related to the login.

Please try to provide more details for us to reproduce your situation.

**Comment by rhfeiyang** [comment]
emmm.. I think it may related to the VPN or something else that can affect the network.
Since I use VPN, I tried to close vpn and then reopen it. Then the result situation is the same(it will not reconnect to overleaf.com again).
Here is the log:
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/c7a0aa0e-3eec-49e4-9654-b0c9cef18fef)

**Comment by rhfeiyang** [comment]
ok, thank you

**Comment by iamhyc** [comment]
@rhfeiyang Hi, we just released `v0.3.1` which try to fix the re-connection issue when `socketio` disconnets. Please give it a try.

**Comment by rhfeiyang** [comment]
eh, it seems that the reconnection does not work well.
Even though it reconnects to overleaf.com, the changes will not be updated to overleaf.

Here is the log:
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/aad0c5eb-1c84-41cc-acd9-884db5e728b0)

Besides, I found after reconnection, it will take the former ones as other people. Because I can see more cursors in the editor but they should not exist.
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/d920e2ff-5b85-451d-8059-d96b04f0fcf0)

**Comment by iamhyc** [comment]
> eh, it seems that the reconnection does not work well. Even though it reconnects to overleaf.com, the changes will not be updated to overleaf.
> 

The provided logs are not related to the problem.

How do you tell that "changes not updated to overleaf"? By viewing the webpage, or close-and-open the same file in vscode? Please give more detailed descriptions.

And is there any error message pop-up window from vscode?

> 
> Besides, I found after reconnection, it will take the former ones as other people. Because I can see more cursors in the editor but they should not exist.

I believe you can also see those cursors on overleaf webpage. Those previous clients simply not disconnected normally.

**Comment by rhfeiyang** [comment]
![img_v2_2784962a-5a79-4a74-90ed-b6218710367g](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/1a94d44b-4158-4ef9-b1d5-1456f4c98131)
![1f8a845d-9837-48b8-91ef-a2b210b3b64c](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/5d1bb53f-91e9-4dbc-a522-34f30d62fcf3)
![c8d4b725-6f3f-4d07-b8f4-cb4c4d45bdb7](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/b1ba3c30-d537-46a1-ab70-f8bd80733385)

And the log for "After some disconnection...", there is a strange error:
![img_v2_f0cd174f-ea03-4a89-9d5b-5e136ee0588g](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/542f0b68-612b-4bac-a2eb-bc7a0c165378)

**Comment by iamhyc** [comment]
@rhfeiyang ok, I got why the duplicate-client thing happened: the status bar icon is registered again when reconnecting.

And according to the 6 times repeated "Disconnected, reconnecting...", it seems like the re-connection never succeeded.

**Comment by rhfeiyang** [comment]
Can you disable local editing when disconnected? This can make sure the things written won't be discarded unexpectedly.

**Comment by iamhyc** [comment]
> Can you disable local editing when disconnected? This can make sure the things written won't be discarded unexpectedly. And what about adding a reconnection button to enable reconnecting manually?

Good idea, I will let user noticed when connection is lost, maybe via the status bar icon.

About the reconnect button, I think it would be better let user re-open the project instead of re-connect.
Like your condition, we don't know what would be the exact cause when the connection is lost.

**Comment by iamhyc** [comment]
Hi @rhfeiyang , we just released `v0.3.2`, the issue about multiple client icon should be fixed.

Please also let us know if reconnect works.

**Comment by rhfeiyang** [comment]
> Hi @rhfeiyang , we just released ~v0.3.2~ `v0.3.3`, the issue about multiple client icon should be fixed.
> 
> Please also let us know if reconnect works.


Eh... It seems that after disconnecting one time, although there won't be more icons, there just **no** icons, and no cursors of other clients...
The reconnect still does not work, though I see you have added the reconnect button and message. After disconnecting for the first time, I click the "reconnect", then it will reconnect successfully for just several seconds, then it automatically continues to disconnect...(
What about changing the reconnect button to restart the whole vscode window?

**Comment by iamhyc** [comment]
@QianrenLi Please have a look at it when you are free. Maybe you can pack a temporary version extension when you prepare the next fix, and upload it in this thread.

**Comment by QianrenLi** [comment]
> > Hi @rhfeiyang , we just released ~v0.3.2~ `v0.3.3`, the issue about multiple client icon should be fixed.
> > Please also let us know if reconnect works.
> 
> Eh... It seems that after disconnecting one time, although there won't be more icons, there just **no** icons, and no cursors of other clients... The reconnect still does not work, though I see you have added the reconnect button and message. After disconnecting for the first time, I click the "reconnect", then it will reconnect successfully for just several seconds, then it automatically continues to disconnect...( What about changing the reconnect button to restart the whole vscode window?

Hi @rhfeiyang, I wonder how many time the disconnect event happens in your test case, i.e. how many times the "Disconnect" printed in the Dev tools, to help me figure out if the disconnect event fires as designed.

Addressing the reload issue, here is a temp package that based on current version where instead of raising the reconnect button, it automatically reconnect and  raise a reload button under multiple disconnect cases.

When you have time, please let me know whether this fix works.

**Comment by rhfeiyang** [comment]
> > > Hi @rhfeiyang , we just released ~v0.3.2~ `v0.3.3`, the issue about multiple client icon should be fixed.
> > > Please also let us know if reconnect works.
> > 
> > 
> > Eh... It seems that after disconnecting one time, although there won't be more icons, there just **no** icons, and no cursors of other clients... The reconnect still does not work, though I see you have added the reconnect button and message. After disconnecting for the first time, I click the "reconnect", then it will reconnect successfully for just several seconds, then it automatically continues to disconnect...( What about changing the reconnect button to restart the whole vscode window?
> 
> Hi @rhfeiyang, I wonder how many time the disconnect event happens in your test case, i.e. how many times the "Disconnect" printed in the Dev tools, to help me figure out if the disconnect event fires as designed.
> 
> Addressing the reload issue, here is a temp package ([overleaf-workshop-0.3.3-test.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13160589/overleaf-workshop-0.3.3-test.zip)) that based on current version where instead of raising the reconnect button, it automatically reconnect and raise a reload button under multiple disconnect cases.
> 
> When you have time, please let me know whether this fix works.

About 3 times? Actually, I just manually disconnect 1 time, and then I reconnect and continue to edit. Then it will continue to disconnect-reconnect 2 or more times with an interval of several seconds.
I will try the package later,

**Comment by QianrenLi** [comment]
Thanks for the information, it seems that the disconnect works just fine and the automatically disconnect might be a result of simply a disconnect trial fail.

**Comment by rhfeiyang** [comment]
> Hi @rhfeiyang , we just released ~v0.3.2~ `v0.3.3`, the issue about multiple client icon should be fixed.
> 
> Please also let us know if reconnect works.

This version seem simply add a disconnect reminder, and it certainly works.
I hope you can add something like "reload window" button?

**Comment by QianrenLi** [comment]
> > Hi @rhfeiyang , we just released ~v0.3.2~ `v0.3.3`, the issue about multiple client icon should be fixed.
> > Please also let us know if reconnect works.
> 
> This version seems simply add a disconnect reminder, and it certainly works. I hope you can add something like "reload window" button?

Hi @rhfeiyang, by mention the disconnect reminder, do you mean is the reconnection do not works ?

As for the reload button, it exist but only raised after a 3 time reconnection-disconnection loop in this version, since I prefer not to disturb user frequently. 

BTW, the reload feature written in `fix-reconnect` branch is currently not included in the master branch and you can local install  ([overleaf-workshop-0.3.3-test.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13160589/overleaf-workshop-0.3.3-test.zip)) to try it out.

If this works for you or not, please let me know.

**Comment by rhfeiyang** [comment]
![1SP)$}MS)L7C_`6C1@J5WM6](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/fa60c8fe-3215-46bd-bee2-2f9869f03933)

It seem that the reconnection still does not work well.
You see, after one reconnect, the reminder is still "not connected", (but the change can be updated), and... there is also 2 cursors(there should only be one)...

Then I continue to disconnect once, then it do not reconnect successfully.

**Comment by rhfeiyang** [comment]
> > ![1SP)$}MS)L7C_`6C1@J5WM6](https://user-images.githubusercontent.com/99195158/278332496-fa60c8fe-3215-46bd-bee2-2f9869f03933.png)
> > It seem that the reconnection still does not work well. You see, after one reconnect, the reminder is still "not connected", (but the change can be updated), and... there is also 2 cursors(there should only be one)...
> > Then I continue to disconnect once, then it do not reconnect successfully.
> 
> Is this performance of `master` branch or the `fix-reconnet` branch ?

By your link https://github.com/iamhyc/Overleaf-Workshop/files/13160589/overleaf-workshop-0.3.3-test.zip

**Comment by QianrenLi** [comment]
Hi @rhfeiyang, sorry for the delay due to some unexpected problems. After some working, the `fix-reconnect` now reconnect at most 3 times in 15s and then will pop out a reload window.  By manually disconnect my network locally, the reconnection seems to work for me.

Still, I wonder if this reconnection could work under a proxy connection. It would be really nice if you were willing to spare time to test this new amendment. ([overleaf-workshop-0.3.3-test-v0.2.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13344021/overleaf-workshop-0.3.3-test-v0.2.zip)).

**Comment by rhfeiyang** [comment]
> Hi @rhfeiyang, sorry for the delay due to some unexpected problems. After some working, the `fix-reconnect` now reconnect at most 3 times in 15s and then will pop out a reload window. By manually disconnect my network locally, the reconnection seems to work for me.
> 
> Still, I wonder if this reconnection could work under a proxy connection. It would be really nice if you were willing to spare time to test this new amendment. ([overleaf-workshop-0.3.3-test-v0.2.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13344021/overleaf-workshop-0.3.3-test-v0.2.zip)).

Sorry for the delay, I am quite busy these days.
The reconnect seem works better now, it seems successfully reconnect at a larger chance.
But I have not seem the popped "reload windows" in the version you gave out.
And the disconnect icon seems never recover to "connected" status after disconnecting for the first time, even after successfully reconnection afterwards.
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/1f465145-4a71-4e9b-a775-618de2c1c0f9)

**Comment by QianrenLi** [comment]
Thanks for the reply !!!

It takes three-times connection failure to pop out the reload windows which is generally 15s.  ( You can exactly see the reconnect information by togger the **dev tools**. )

As for the status icon, it supposed to update itself automatically. If the status bar do not automatically changes itself after a while (like 3s), please let me know.

**Comment by rhfeiyang** [comment]
> Thanks for the reply !!!
> 
> It takes three-times connection failure to pop out the reload windows which is generally 15s. ( You can exactly see the reconnect information by togger the **dev tools**. )
> 
> As for the status icon, it supposed to update itself automatically. If the status bar do not automatically changes itself after a while (like 3s), please let me know.

It actually does not automatically change itself

**Comment by QianrenLi** [comment]
May I ask is there any log like this in the dev tools and is `SocketIOAPI: connected` exist to help me find out where goes wrong.
```
Disconnected
Reconnecting ...
SocketIOAPI: connected
```

**Comment by rhfeiyang** [comment]
> May I ask is there any log like this in the dev tools and is `SocketIOAPI: connected` exist to help me find out what goes wrong.
> 
> ```
> Disconnected
> Reconnecting ...
> SocketIOAPI: connected
> ```

![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/609338e0-7abd-4825-adba-a93ee8aa2498)
Will this help?

**Comment by QianrenLi** [comment]
That's quit helpful and it might comes from a event fire erorr. Can you reproduce the problem with this packege where I place additional log information to check the event status.  ([overleaf-workshop-0.3.3-test-v0.3.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13391130/overleaf-workshop-0.3.3-test-v0.3.zip))

**Comment by QianrenLi** [comment]
Thanks for the information, from the log information it seems the reconnect event fires as normal thus logically it should work.

Since your log shows the status information has changed and the status updating procedure recursively call itself each 0.5s, the updating will not be blocked or modified when disconnect or reconnect and it should change the status in a while.

If there are any possibility that the status not working, it might come from status updating itself. In case of this, I log the status update also and if you have time please try this to see where the problem locates from the log. ( [overleaf-workshop-0.3.3-test-v0.4.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13398826/overleaf-workshop-0.3.3-test-v0.4.zip)  )

**Comment by rhfeiyang** [comment]
> Thanks for the information, from the log information it seems the reconnect event fires as normal thus logically it should work.
> 
> Since your log shows the status information has changed and the status updating procedure recursively call itself each 0.5s, the updating will not be blocked or modified when disconnect or reconnect and it should change the status in a while.
> 
> If there are any possibility that the status not working, it might come from status updating itself. In case of this, I log the status update also and if you have time please try this to see where the problem locates from the log. ( [overleaf-workshop-0.3.3-test-v0.4.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13398826/overleaf-workshop-0.3.3-test-v0.4.zip) )

![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/2fafb267-433f-4c87-b722-ce3abd7fbe59)
[log.txt](https://github.com/iamhyc/Overleaf-Workshop/files/13399919/log.txt)

What about this one

**Comment by rhfeiyang** [comment]
> > Thanks for the information, from the log information it seems the reconnect event fires as normal thus logically it should work.
> > Since your log shows the status information has changed and the status updating procedure recursively call itself each 0.5s, the updating will not be blocked or modified when disconnect or reconnect and it should change the status in a while.
> > If there are any possibility that the status not working, it might come from status updating itself. In case of this, I log the status update also and if you have time please try this to see where the problem locates from the log. ( [overleaf-workshop-0.3.3-test-v0.4.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13398826/overleaf-workshop-0.3.3-test-v0.4.zip) )
> 
> ![image](https://user-images.githubusercontent.com/99195158/283991413-2fafb267-433f-4c87-b722-ce3abd7fbe59.png) [log.txt](https://github.com/iamhyc/Overleaf-Workshop/files/13399919/log.txt)
> 
> What about this one

I tried it again just now. The strange thing is that the status icon can recover itself now. And I tried disconnecting several times, the reconnect, along with the status icon, now works normally.

**Comment by QianrenLi** [comment]
Since the reconnect problem is fixed, i'll close this issue in a while.

**Comment by rhfeiyang** [comment]
Eh. the reconnection seems to still have a bug. After reconnection, there will be two cursors: one is my local computer(white), and the other one is a purple one(from remote), which is also my account. And the purple one will just follow the white one.
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/0ed7e89f-01f9-4a67-9cfe-7ea486b9541f)

**Comment by iamhyc** [comment]
> Eh. the reconnection seems to still have a bug. After reconnection(by reload button popped), there will be two cursors: one is my local computer(white), and the other one is a purple one(from remote), which is also my account. And the purple one will just follow the white one.

We are aware of the problem. The problem is now tracked under issue #51
